import FooterComponent from '@/components/FooterComponent'
import './globals.css'
import { Inter } from 'next/font/google'
import NarbarComponent from '@/components/NarbarComponent'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NarbarComponent/>
        {children}
        <FooterComponent />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></Script>
      </body>
    </html>
  )
}
